language: scala

scala:
  - "2.10.6"

jdk:
  - oraclejdk8

script:
  - sbt -J-XX:ReservedCodeCacheSize=128m ++$TRAVIS_SCALA_VERSION ";test:compile"
  - git diff --exit-code --color || { echo "[error] Unformatted code found. Please run 'test:compile' and commit the reformatted code."; false; } && sbt -J-XX:ReservedCodeCacheSize=128m ++$TRAVIS_SCALA_VERSION ";test"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

deploy:
  provider: script
  script:
    - sbt -J-XX:ReservedCodeCacheSize=128m ++$TRAVIS_SCALA_VERSION publish
  on:
    tags: true
    repo: akka/akka-paradox

env:
  global:
    # encrypt with: travis encrypt BINTRAY_USER=...
    - secure: "TZ5/EpN2ZlMaEoY3A/tSkhia6pJm8dAOs5Be2uE7GVl9O/frE8fgp96G8kI6PicexM5Awwpkf94o50FVWx+89GyXVDHMPlOUIdiPANPo7YlNjgovzVAF5i6HK5nqpJWetdp+i/JanMDCJ9Cu9A+vE6KTUat1ye0qKLW2s8TOWMpL9Zz/fq1eQmZNvXOzBwMVYfDLXILYYOw5AdeS8o2OYw+rpymTU5oHwT0xOAdTAYSUqKJGPeWzg7wI/npZmCJ7h/JS3rZxdEWmWSRg+6zIOOtHm5ggPB4/TkoT9me/OobYex53tmeowRBFGVojfPK0UGvqJtMuMkv+GMu9oqBiVrf+XNMwDc8Awe0ewv9CRfTY4GnqLicePFS83Xo9KT1PqxzeEAO+kbL40gIZgoySvlwrgfGBvXRm4ucAjDB2ZBa6wGEJwWDYISH7yXJ2NVSlGQ1DpepwwuDfrKCuwbZLbK1wpS/KkOW4vFlHkYbiPmwmTtnxpb0zhzzCCemb9yDn395IDHCRzGolY3Q9ic6JQlxKXPBDkzwG/Qb27y5XdQ0WKow+9EvWGzbHFnsAzR7XtKL2oOUWLpD4G1D7/nP/zwAXifrN2O5aoM0wjXWDBAtaOXhd2D3xy9uS3zC0r2v9Ht43L+Syb962Dc0MvGHe0rfXi08TafsQEi+xiK2xC8o="
    # encrypt with: travis encrypt BINTRAY_PASS=...
    - secure: "oKne77qM4hck9A8u+xMuUpevAZGQXL3u5hV/ArYFu9FL46l3/bMxzQg3ijeQxim6tM01lsTD4bAq6ffLBI3pNufeZt8q6Jcks3lreuWSwT+CSqJs91E/IavcKa+32e9jEaXkbcatZ3ggXnhWMt9uAl1JHzh9qNqvHItpnRl/WlrqfgXV6e+KGDvujkf6gmlQ7/x2kHvPg61T2ro+mv4xLI+WZPIdONOmbReWHawQw/pltvv1S42av6FanuidywpFmkDMAiwjuU0VK73+jJOyij+kwbWoS/p3U4t1Kh5RXKqa2A5D9Ba4SPBE5MOfW30ZzeZV+94FfogsnK7EgIh9cT9LCiWL7VkRdl7AfxxiRhISYP2uaI1Rbo/6klf3Ib2zqvQr4s8ePdeOXGotcR2M0SVtASiv7F/bcsOvjwFdre7hao5IqsfT/mUzGKc0Id2PD/ZRF7sCxgdAQ2B4wGBwbEntx2JLLW8CByfNKSrd8U21KytaMqSBClFqlHiTL80OvukbGdJvHY8gDrvVkQEyhZ/olOIUzF5dei4jZhg7LaxKlKf1TLBq7QI9nX3ayRRLIxBjSJiiIbIAJsHbnvzR7/vbjPhwyWBFiOBkpIzuNYPrTP3C0nRkokoJXY+ifEpPvmmRjd4CK2wO1tkdQ5CsEIQdTL963YtIeziJTz2RFPA="
